/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandStoryRouteImport } from './routes/brand-story'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ShippingLogisticsRouteImport } from './routes/shipping-logistics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as WholesaleFaqRouteImport } from './routes/wholesale-faq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStoryRoute = BrandStoryRouteImport.update({
  id: '/brand-story',
  path: '/brand-story',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingLogisticsRoute = ShippingLogisticsRouteImport.update({
  id: '/shipping-logistics',
  path: '/shipping-logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleFaqRoute = WholesaleFaqRouteImport.update({
  id: '/wholesale-faq',
  path: '/wholesale-faq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-story': typeof BrandStoryRoute
  '/categories': typeof CategoriesRoute
  '/inquiry': typeof InquiryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-logistics': typeof ShippingLogisticsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wholesale-faq': typeof WholesaleFaqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-story': typeof BrandStoryRoute
  '/categories': typeof CategoriesRoute
  '/inquiry': typeof InquiryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-logistics': typeof ShippingLogisticsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wholesale-faq': typeof WholesaleFaqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-story': typeof BrandStoryRoute
  '/categories': typeof CategoriesRoute
  '/inquiry': typeof InquiryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-logistics': typeof ShippingLogisticsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wholesale-faq': typeof WholesaleFaqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand-story'
    | '/categories'
    | '/inquiry'
    | '/privacy-policy'
    | '/shipping-logistics'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/wholesale-faq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand-story'
    | '/categories'
    | '/inquiry'
    | '/privacy-policy'
    | '/shipping-logistics'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/wholesale-faq'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand-story'
    | '/categories'
    | '/inquiry'
    | '/privacy-policy'
    | '/shipping-logistics'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/wholesale-faq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandStoryRoute: typeof BrandStoryRoute
  CategoriesRoute: typeof CategoriesRoute
  InquiryRoute: typeof InquiryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShippingLogisticsRoute: typeof ShippingLogisticsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WholesaleFaqRoute: typeof WholesaleFaqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-story': {
      id: '/brand-story'
      path: '/brand-story'
      fullPath: '/brand-story'
      preLoaderRoute: typeof BrandStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-logistics': {
      id: '/shipping-logistics'
      path: '/shipping-logistics'
      fullPath: '/shipping-logistics'
      preLoaderRoute: typeof ShippingLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale-faq': {
      id: '/wholesale-faq'
      path: '/wholesale-faq'
      fullPath: '/wholesale-faq'
      preLoaderRoute: typeof WholesaleFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandStoryRoute: BrandStoryRoute,
  CategoriesRoute: CategoriesRoute,
  InquiryRoute: InquiryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShippingLogisticsRoute: ShippingLogisticsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WholesaleFaqRoute: WholesaleFaqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
